In [2]:
import numpy as np

In [5]:
N = 128
theta = np.arange (0, 2 * np.pi, np.pi/(N/2))
matrix = np.zeros((N, N))
for i in range (0,N):
    for j in range (0,N):
        matrix [i][j] = np.abs(np.sin((theta[i] - theta [j])))
print (matrix)

[[0.         0.04906767 0.09801714 ... 0.14673047 0.09801714 0.04906767]
 [0.04906767 0.         0.04906767 ... 0.19509032 0.14673047 0.09801714]
 [0.09801714 0.04906767 0.         ... 0.24298018 0.19509032 0.14673047]
 ...
 [0.14673047 0.19509032 0.24298018 ... 0.         0.04906767 0.09801714]
 [0.09801714 0.14673047 0.19509032 ... 0.04906767 0.         0.04906767]
 [0.04906767 0.09801714 0.14673047 ... 0.09801714 0.04906767 0.        ]]


In [6]:
N = 128
theta = np.arange (0, 2 * np.pi, np.pi/(N/2))
matrix = np.zeros((N, N))
for i in range (0,N):
    for j in range (0,N):
        matrix [i][j] = np.abs(np.sin((theta[j] - theta [i])))
print (matrix)

[[0.         0.04906767 0.09801714 ... 0.14673047 0.09801714 0.04906767]
 [0.04906767 0.         0.04906767 ... 0.19509032 0.14673047 0.09801714]
 [0.09801714 0.04906767 0.         ... 0.24298018 0.19509032 0.14673047]
 ...
 [0.14673047 0.19509032 0.24298018 ... 0.         0.04906767 0.09801714]
 [0.09801714 0.14673047 0.19509032 ... 0.04906767 0.         0.04906767]
 [0.04906767 0.09801714 0.14673047 ... 0.09801714 0.04906767 0.        ]]
